---
version: "2"

jobs:
  "Build Docker image":
    machine:
      docker_layer_caching: true
    steps:
      - type: checkout
      - run: docker build .

  "Release":
    docker:
      - image: circleci/node:8
    steps:
      - type: checkout
      - run: sudo npm install -g semantic-release
      - run: semantic-release

workflows:
  version: 2
  PR:
    jobs:
      - "Build Docker image"
      - "Release":
          requires:
            - "Build Docker image"
          filters:
            branches:
              only:
                - master
